import * as THREE from 'three';
import { AgentState } from '../agents/AgentStore';
import { BuildingArchetype, type Building } from '../generation/CityGenerator';
import { lifelineWorkplaceForPoi } from '../world/LifelineWorkforce';
import { POICategory } from '../world/POI';
import { workplaceStaffingForPoi } from '../world/WorkplaceProductivityTuning';
import type { World } from '../world/World';
import { cool, good, muted, setSegment, severityColor, updateMesh, warn, type ExpansionState, type OverlayInternals } from './CityDiagnosticOverlayExpansionCommon';

export function refreshEmploymentStaffing(state: ExpansionState, world: World): void {
  const ui = state.manager as unknown as OverlayInternals, n = ui.buildings.length;
  const cap = new Float64Array(n), assigned = new Float64Array(n), present = new Float64Array(n), scheduled = new Float64Array(n), lifeNeed = new Float64Array(n), lifeOnDuty = new Float64Array(n);
  let totalCap=0,totalAssigned=0,totalPresent=0,totalScheduled=0,lifeShort=0;
  for (const poi of world.city.poi.all()) { if (poi.category !== POICategory.Work || poi.capacity <= 0 || poi.buildingId < 0 || poi.buildingId >= n) continue; const staffing = workplaceStaffingForPoi(world.city.poi, poi.id), b = poi.buildingId; cap[b]+=staffing.capacity; assigned[b]+=staffing.assigned; present[b]+=staffing.present; scheduled[b]+=staffing.scheduled; totalCap+=staffing.capacity; totalAssigned+=staffing.assigned; totalPresent+=staffing.present; totalScheduled+=staffing.scheduled; const life=lifelineWorkplaceForPoi(world.city.poi,poi.id); if(life){lifeNeed[b]+=life.concurrentStaff;lifeOnDuty[b]+=staffing.onDuty;lifeShort+=Math.max(0,life.concurrentStaff-staffing.onDuty);} }
  let shortageBuildings=0;
  for(let b=0;b<n;b++){ if(cap[b]<=0){ui.buildingMesh.setColorAt(b,muted);continue;} const assignShort=1-Math.min(1,assigned[b]/Math.max(1,cap[b])), attendShort=scheduled[b]>0?1-Math.min(1,present[b]/scheduled[b]):0, critical=lifeNeed[b]>0?1-Math.min(1,lifeOnDuty[b]/lifeNeed[b]):0, sev=Math.max(assignShort*0.65,attendShort,critical); if(sev>0.25)shortageBuildings++; ui.buildingMesh.setColorAt(b,severityColor(sev)); }
  updateMesh(ui.buildingMesh); ui.summary.textContent=`定員充足 ${totalCap>0?(totalAssigned/totalCap*100).toFixed(1):'0.0'}% / 出勤 ${totalScheduled>0?(totalPresent/totalScheduled*100).toFixed(1):'100.0'}% / 不足建物${shortageBuildings} / ライフライン不足${lifeShort.toFixed(0)}人`;
}

export function refreshEmploymentCommute(state: ExpansionState, world: World): void {
  const ui=state.manager as unknown as OverlayInternals, s=world.store, stride=Math.max(1,Math.ceil(s.count/1800)); let flow=0,total=0,walk=0,car=0,bus=0,rail=0;
  const carColor=new THREE.Color(0xe89a3c),busColor=new THREE.Color(0x4e9fe5),railColor=new THREE.Color(0x9566dd);
  for(let a=0;a<s.count;a++){ const home=s.homePOI[a],work=s.workPOI[a],goal=s.goalPOI[a]; if(work<0||(goal!==work&&goal!==home))continue; const st=s.state[a]; if(st===AgentState.Idle||st===AgentState.Engaged)continue; const target=world.city.poi.get(goal); total++; let color=good; if(st===AgentState.Driving||st===AgentState.ToVehicle){car++;color=carColor;}else if(st===AgentState.ToBusStop||st===AgentState.WaitingBus||st===AgentState.OnBus){bus++;color=busColor;}else if(st===AgentState.ToRailStation||st===AgentState.WaitingTrain||st===AgentState.OnTrain){rail++;color=railColor;}else walk++; if(a%stride!==0||flow>=state.flowMesh.instanceMatrix.count)continue; setSegment(state.flowMesh,flow,s.posX[a],s.posZ[a],target.x,target.z,0.44,1.6);state.flowMesh.setColorAt(flow,color);flow++; }
  state.flowMesh.count=flow;updateMesh(state.flowMesh);ui.summary.textContent=`通勤中${total} / 徒歩${walk} / 車${car} / バス${bus} / 鉄道${rail} / 描画Flow${flow}`;
}

const COLORS={residential:new THREE.Color(0x4c8bd8),office:new THREE.Color(0x58b8c7),commercial:new THREE.Color(0xe9a23b),public:new THREE.Color(0xb171d1),industry:new THREE.Color(0xb77745),leisure:new THREE.Color(0x61ad68),infrastructure:new THREE.Color(0xe4d14b)} as const;
function buildingUse(world:World,b:Building,facilityIds:Set<number>):{key:keyof typeof COLORS;color:THREE.Color}{ void world; const r=b as Building&{infrastructureLabel?:string;intendedUse?:string}; if(r.infrastructureLabel||r.intendedUse==='power')return{key:'infrastructure',color:COLORS.infrastructure}; if(b.archetype===BuildingArchetype.Factory||b.archetype===BuildingArchetype.Warehouse)return{key:'industry',color:COLORS.industry}; if(facilityIds.has(b.id))return{key:'public',color:COLORS.public}; if(b.category===POICategory.Home)return{key:'residential',color:COLORS.residential}; if(b.category===POICategory.Food||b.category===POICategory.Retail)return{key:'commercial',color:COLORS.commercial}; if(b.category===POICategory.Leisure)return{key:'leisure',color:COLORS.leisure}; if(b.category===POICategory.Health||b.category===POICategory.Education)return{key:'public',color:COLORS.public}; return{key:'office',color:COLORS.office}; }
export function refreshLandUseCategory(state:ExpansionState,world:World):void{ const ui=state.manager as unknown as OverlayInternals,counts=new Map<string,number>(),facilityIds=new Set(world.city.facilities.map(f=>f.buildingId)); for(let i=0;i<ui.buildings.length;i++){const mapped=buildingUse(world,ui.buildings[i],facilityIds);ui.buildingMesh.setColorAt(i,mapped.color);counts.set(mapped.key,(counts.get(mapped.key)??0)+1);}updateMesh(ui.buildingMesh);ui.summary.textContent=`住宅${counts.get('residential')??0} / 業務${counts.get('office')??0} / 商業${counts.get('commercial')??0} / 公共${counts.get('public')??0} / 産業物流${counts.get('industry')??0} / 余暇${counts.get('leisure')??0} / インフラ${counts.get('infrastructure')??0}`; }
export function refreshLandUseUtilization(state:ExpansionState,world:World):void{ const ui=state.manager as unknown as OverlayInternals,n=ui.buildings.length,used=new Float64Array(n),cap=new Float64Array(n),scratch=new THREE.Color(); for(const p of world.city.poi.all()){if(p.capacity<=0||p.buildingId<0||p.buildingId>=n)continue;const occ=p.category===POICategory.Work?workplaceStaffingForPoi(world.city.poi,p.id).present:p.occupancy;used[p.buildingId]+=Math.max(0,occ);cap[p.buildingId]+=p.capacity;}let totalU=0,totalC=0,active=0;for(let i=0;i<n;i++){if(cap[i]<=0){ui.buildingMesh.setColorAt(i,muted);continue;}const ratio=Math.max(0,Math.min(1,used[i]/cap[i]));ui.buildingMesh.setColorAt(i,scratch.copy(cool).lerp(warn,Math.sqrt(ratio)));totalU+=used[i];totalC+=cap[i];if(ratio>0.05)active++;}updateMesh(ui.buildingMesh);ui.summary.textContent=`POI利用 ${totalU.toFixed(0)}/${totalC.toFixed(0)} (${totalC>0?(totalU/totalC*100).toFixed(1):'0.0'}%) / 稼働建物${active}`; }
