import * as THREE from 'three';
import type { RoadNetwork } from '../traffic/RoadNetwork';
import { World } from '../world/World';
import { EnhancedRenderer, type RenderingLodStats } from './EnhancedRenderer';
import { OverlayManager } from './CityDiagnosticOverlay';
import {
  appendExtendedOptions, createExpansionState, densityColor, extendedById, extendedMode, gridIndex,
  setExpansionOpacity, updateMesh, type ExpansionState, type OverlayInternals,
} from './CityDiagnosticOverlayExpansionCommon';
import { accessibilityDistances, refreshAccessibility, refreshLogisticsFleet, refreshLogisticsSupply } from './CityDiagnosticOverlayLogisticsAccess';
import { refreshEmploymentCommute, refreshEmploymentStaffing, refreshLandUseCategory, refreshLandUseUtilization } from './CityDiagnosticOverlaySociety';
import { refreshPopulation, refreshTransitCoverage, refreshTransitLoad } from './CityDiagnosticOverlayTransitPopulation';
import { PerformanceMonitor, type RenderProfileSample } from './PerformanceMonitor';

interface SimProfileSnapshot { totalMs:number; workerMs:number; poiWorkerMs:number; trafficMs:number; busMs:number; logisticsMs:number; astarWalkMs:number; astarWalkCount:number; astarWalkMaxMs:number; astarVehicleMs:number; astarVehicleCount:number; astarVehicleMaxMs:number; steps:number; }
interface DeveloperSnapshot { frameMs:number; fps:number; render:RenderProfileSample; lod:RenderingLodStats; backlogSec:number; simBusy:boolean; sim:SimProfileSnapshot; }
const stateByManager=new WeakMap<OverlayManager,ExpansionState>(),worldByNet=new WeakMap<RoadNetwork,World>(),rendererByNet=new WeakMap<RoadNetwork,EnhancedRenderer>(),developerByWorld=new WeakMap<World,DeveloperSnapshot>(),developerEnabledWorlds=new WeakSet<World>();

function ensureWorld(state:ExpansionState):World|null{if(state.world)return state.world;const ui=state.manager as unknown as OverlayInternals;state.world=worldByNet.get(ui.net)??null;return state.world;}
function applyVisibility(manager:OverlayManager):void{
  const state=stateByManager.get(manager);if(!state)return;const ui=manager as unknown as OverlayInternals,mode=ui.modeValue,world=ensureWorld(state);if(world){developerEnabledWorlds.delete(world);if(mode==='developer-diagnostics')developerEnabledWorlds.add(world);}for(const mesh of[state.gridMesh,state.routeMesh,state.markerMesh,state.coverageMesh,state.flowMesh,state.chunkMesh])mesh.visible=false;if(!extendedMode(mode))return;
  ui.group.visible=true;ui.trafficMesh.visible=false;ui.buildingMesh.visible=false;if(ui.powerLineMesh)ui.powerLineMesh.visible=false;if(ui.assetMesh)ui.assetMesh.visible=false;
  if(mode==='transit-load'){state.routeMesh.visible=true;state.markerMesh.visible=true;}else if(mode==='transit-coverage'){state.routeMesh.visible=true;state.markerMesh.visible=true;state.coverageMesh.visible=true;}else if(mode==='population-density'||mode==='population-daynight')state.gridMesh.visible=true;else if(mode==='employment-staffing'||mode==='landuse-category'||mode==='landuse-utilization'||mode==='logistics-supply'||mode.startsWith('access-'))ui.buildingMesh.visible=true;else if(mode==='employment-commute')state.flowMesh.visible=true;else if(mode==='logistics-fleet'){ui.trafficMesh.visible=true;state.markerMesh.visible=true;}else if(mode==='developer-diagnostics'){state.gridMesh.visible=true;state.chunkMesh.visible=true;}
  ui.legend.textContent=extendedById.get(mode)?.legend??'';ui.summary.textContent=world?'診断Snapshotを更新中':'Worldへの接続待ち';
}
function refreshDeveloper(state:ExpansionState,world:World):void{
  const ui=state.manager as unknown as OverlayInternals,cells=state.gridCols*state.gridRows,agents=new Uint32Array(cells),vehicles=new Uint32Array(cells);for(let a=0;a<world.store.count;a++)agents[gridIndex(state,world.store.posX[a],world.store.posZ[a])]++;for(let v=0;v<world.vehicles.count;v++)vehicles[gridIndex(state,world.vehicles.posX[v],world.vehicles.posZ[v])]++;let max=1;for(let i=0;i<cells;i++)max=Math.max(max,agents[i]+vehicles[i]*2);for(let i=0;i<cells;i++)state.gridMesh.setColorAt(i,densityColor(Math.sqrt((agents[i]+vehicles[i]*2)/max)));updateMesh(state.gridMesh);
  const lodColors=[new THREE.Color(0x47c878),new THREE.Color(0xe5cb4c),new THREE.Color(0xee8b47),new THREE.Color(0xd45a70)] as const;for(let i=0;i<state.chunks.length;i++){const base=i*4,color=lodColors[state.chunks[i].lod];for(let side=0;side<4;side++)state.chunkMesh.setColorAt(base+side,color);}updateMesh(state.chunkMesh);
  const dev=developerByWorld.get(world);if(!dev){const lod=state.renderer?.getLodStats();ui.summary.textContent=lod?`LOD B ${lod.buildings.join('/')} / A ${lod.agents.join('/')} / V ${lod.vehicles.join('/')} / 性能Snapshot待ち`:'性能Snapshot待ち';return;}const sim=dev.sim;ui.summary.textContent=`FPS ${dev.fps.toFixed(0)} / Frame ${dev.frameMs.toFixed(1)}ms / Render ${dev.render.totalMs.toFixed(1)}ms / Sim ${sim.totalMs.toFixed(1)}ms/${sim.steps}step / A* walk ${sim.astarWalkMs.toFixed(1)}ms/${sim.astarWalkCount} max${sim.astarWalkMaxMs.toFixed(2)} / vehicle ${sim.astarVehicleMs.toFixed(1)}ms/${sim.astarVehicleCount} max${sim.astarVehicleMaxMs.toFixed(2)} / LOD B ${dev.lod.buildings.join('/')} A ${dev.lod.agents.join('/')} V ${dev.lod.vehicles.join('/')} / backlog ${(dev.backlogSec*1000).toFixed(0)}ms${dev.simBusy?' BUSY':''}`;
}
function refreshExtended(manager:OverlayManager,now:number,force:boolean):void{
  const state=stateByManager.get(manager);if(!state)return;const ui=manager as unknown as OverlayInternals,mode=ui.modeValue;if(!extendedMode(mode)||(!force&&now-state.lastRefreshAt<500))return;state.lastRefreshAt=now;const world=ensureWorld(state);if(!world){ui.summary.textContent='Worldへの接続待ち';return;}const started=performance.now();
  if(mode==='transit-load')refreshTransitLoad(state,world);else if(mode==='transit-coverage')refreshTransitCoverage(state,world,(s,w)=>accessibilityDistances(s,w,'transit'));else if(mode==='population-density')refreshPopulation(state,world,false);else if(mode==='population-daynight')refreshPopulation(state,world,true);else if(mode==='employment-staffing')refreshEmploymentStaffing(state,world);else if(mode==='employment-commute')refreshEmploymentCommute(state,world);else if(mode==='landuse-category')refreshLandUseCategory(state,world);else if(mode==='landuse-utilization')refreshLandUseUtilization(state,world);else if(mode==='logistics-supply')refreshLogisticsSupply(state,world);else if(mode==='logistics-fleet')refreshLogisticsFleet(state,world);else if(mode==='access-station')refreshAccessibility(state,world,'station','駅');else if(mode==='access-work')refreshAccessibility(state,world,'work','職場');else if(mode==='access-commercial')refreshAccessibility(state,world,'commercial','商業');else if(mode==='access-public')refreshAccessibility(state,world,'public','公共施設');else refreshDeveloper(state,world);
  const cost=performance.now()-started;state.refreshCostEmaMs=state.refreshCostEmaMs<=0?cost:state.refreshCostEmaMs*0.82+cost*0.18;if(ui.summary.textContent&&!ui.summary.textContent.includes('診断更新'))ui.summary.textContent+=` / 診断更新 ${state.refreshCostEmaMs.toFixed(2)}ms@2Hz`;
}

const worldProto=World.prototype as unknown as Record<string,unknown>;if(!worldProto.__machiSimDiagnosticOverlayWorldV114){const previous=worldProto.populate as World['populate'];worldProto.populate=function(this:World,...args:Parameters<World['populate']>):void{previous.apply(this,args);worldByNet.set(this.city.net,this);};worldProto.__machiSimDiagnosticOverlayWorldV114=true;}
const rendererProto=EnhancedRenderer.prototype as unknown as Record<string,unknown>;if(!rendererProto.__machiSimDiagnosticOverlayExpansionRendererV114){const previous=rendererProto.buildStatic as EnhancedRenderer['buildStatic'];rendererProto.buildStatic=function(this:EnhancedRenderer,...args:Parameters<EnhancedRenderer['buildStatic']>):void{rendererByNet.set(args[1],this);previous.apply(this,args);};rendererProto.__machiSimDiagnosticOverlayExpansionRendererV114=true;}
const monitorProto=PerformanceMonitor.prototype as unknown as Record<string,unknown>;if(!monitorProto.__machiSimDiagnosticOverlayPerformanceV114){const previous=monitorProto.update as PerformanceMonitor['update'];monitorProto.update=function(this:PerformanceMonitor,...args:Parameters<PerformanceMonitor['update']>):void{previous.apply(this,args);const internal=this as unknown as{world:World;profiler:{latest:SimProfileSnapshot}};if(!developerEnabledWorlds.has(internal.world))return;developerByWorld.set(internal.world,{frameMs:args[1],fps:args[2],render:{...args[3]},lod:{buildings:[...args[4].buildings] as[number,number,number,number],agents:[...args[4].agents] as[number,number],vehicles:[...args[4].vehicles] as[number,number]},backlogSec:args[5],simBusy:args[6],sim:{...internal.profiler.latest}});};monitorProto.__machiSimDiagnosticOverlayPerformanceV114=true;}
const overlayProto=OverlayManager.prototype as unknown as Record<string,unknown>;if(!overlayProto.__machiSimDiagnosticOverlayExpansionV114){const createUi=overlayProto.createUi as(this:OverlayManager)=>{panel:HTMLDivElement;select:HTMLSelectElement;opacityInput:HTMLInputElement;legend:HTMLDivElement;summary:HTMLDivElement};overlayProto.createUi=function(this:OverlayManager){const ui=createUi.call(this);appendExtendedOptions(ui.select);const internal=this as unknown as OverlayInternals;stateByManager.set(this,createExpansionState(this,worldByNet.get(internal.net)??null,rendererByNet.get(internal.net)??null));return ui;};const visibility=overlayProto.applyModeVisibility as(this:OverlayManager)=>void;overlayProto.applyModeVisibility=function(this:OverlayManager):void{visibility.call(this);applyVisibility(this);};const refresh=overlayProto.refresh as OverlayManager['refresh'];overlayProto.refresh=function(this:OverlayManager,now=performance.now(),force=false):void{refresh.call(this,now,force);refreshExtended(this,now,force);};const opacity=overlayProto.setOpacity as OverlayManager['setOpacity'];overlayProto.setOpacity=function(this:OverlayManager,value:number):void{opacity.call(this,value);const state=stateByManager.get(this);if(state)setExpansionOpacity(state,value);};overlayProto.__machiSimDiagnosticOverlayExpansionV114=true;}
